name: Docker CI/CD 'latest'

on:
  push:
    branches: 
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag briankopp/k8s-sqs-autoscaler:latest
    - name: Push the Docker image
      run: docker push briankopp/k8s-sqs-autoscaler:latest
